package com.ecoomerce.sportscenter.entity;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.redis.core.RedisHash;

import java.util.ArrayList;
import java.util.List;

/**
 * Basket — Redis entity representing a user's shopping basket.
 *
 * IMPORTANT: This is NOT a JPA/MySQL entity. It is stored in Redis (an in-memory key-value store),
 * NOT in the relational database. Redis is used because baskets are:
 *   - Session-scoped (temporary — they expire or get cleared at checkout)
 *   - Write-heavy (items are frequently added/removed/updated)
 *   - Better modelled as a document than as relational rows
 *
 * @RedisHash("Basket") : tells Spring Data Redis to store instances under the Redis hash
 *                        key "Basket:<id>" (e.g. "Basket:abc123")
 * @Data               : auto-generates getters, setters, equals, hashCode, toString (Lombok)
 * @NoArgsConstructor  : generates a no-arg constructor (required by Spring Data Redis)
 */
@Data
@NoArgsConstructor
@RedisHash("Basket")       // Redis storage key prefix — objects stored as "Basket:<id>"
public class Basket {

    @Id                    // Marks this field as the Redis hash key (Spring Data Redis @Id, not JPA @Id)
    private String id;     // Unique basket identifier (e.g. a UUID or CUID generated by the Angular client)

    /**
     * The list of items currently in the basket.
     * Initialised as an empty ArrayList so new baskets start with no items
     * without requiring a null check in the service layer.
     */
    private List<BasketItem> items = new ArrayList<>();

    /**
     * Convenience constructor — creates a basket with the given ID and an empty item list.
     * Used in BasketServiceImpl when creating a new basket.
     *
     * @param id unique identifier for this basket (generated by the client)
     */
    public Basket(String id){
        this.id = id;
    }
}
