package com.ecoomerce.sportscenter.repository;

import com.ecoomerce.sportscenter.entity.Basket;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

/**
 * BasketRepository — Spring Data Redis repository for Basket entity.
 *
 * IMPORTANT: This extends CrudRepository (NOT JpaRepository) because Basket is stored in
 * Redis, not MySQL. Spring Data Redis provides the CrudRepository implementation
 * that serialises/deserialises Basket objects to/from Redis hashes.
 *
 * CrudRepository<Basket, String> automatically provides:
 *   - findById(String id)      → Optional<Basket>  (reads "Basket:<id>" from Redis)
 *   - findAll()                → Iterable<Basket>  (scans all "Basket:*" keys)
 *   - save(Basket basket)      → Basket            (writes the basket to Redis)
 *   - deleteById(String id)    → void              (removes "Basket:<id>" from Redis)
 *   - existsById(String id)    → boolean
 *
 * The String type parameter is the type of the @Id field in Basket
 * (the basket ID is a string UUID/CUID generated by the Angular client).
 *
 * No custom query methods are needed here — the CRUD operations cover all
 * basket management requirements (get, save/update, delete).
 *
 * @Repository : declares this as a Spring Data repository bean
 */
@Repository
public interface BasketRepository extends CrudRepository<Basket, String> {
    // All needed operations are inherited from CrudRepository
    // Spring Data Redis auto-implements this interface at startup
}
