package com.ecoomerce.sportscenter.controller;

import com.ecoomerce.sportscenter.entity.Basket;
import com.ecoomerce.sportscenter.entity.BasketItem;
import com.ecoomerce.sportscenter.model.BasketItemResponse;
import com.ecoomerce.sportscenter.model.BasketResponse;
import com.ecoomerce.sportscenter.service.BasketService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.stream.Collectors;

/**
 * BasketController — REST controller for shopping basket endpoints.
 *
 * Base URL: /api/baskets
 *
 * The basket is stored in Redis (not MySQL). Each basket is identified by a
 * client-generated CUID/UUID string, allowing the Angular frontend to manage
 * basket identity without needing server-side sessions.
 *
 * Endpoints:
 *   GET    /api/baskets            — list all baskets (debugging / admin use)
 *   GET    /api/baskets/{basketId} — fetch a specific basket by ID
 *   DELETE /api/baskets/{basketId} — delete a basket (e.g. after checkout completes)
 *   POST   /api/baskets            — create a new basket or update an existing one
 *
 * Note: The POST endpoint handles both create and update because Redis's save()
 * is an upsert — it creates a new key if it doesn't exist, or overwrites if it does.
 * Angular always sends the full basket state on every change (add/remove/quantity).
 *
 * @RestController : combines @Controller + @ResponseBody — all methods return JSON
 * @RequestMapping : all routes prefixed with "/api/baskets"
 */
@RestController
@RequestMapping("/api/baskets")
public class BasketController {
    private final BasketService basketService; // delegates to Redis via BasketRepository

    /**
     * Constructor injection — Spring injects the BasketService dependency.
     *
     * @param basketService handles all basket CRUD operations against Redis
     */
    public BasketController(BasketService basketService) {
        this.basketService = basketService;
    }

    /**
     * getAllBaskets — GET /api/baskets
     *
     * Returns all baskets currently stored in Redis. Primarily useful for
     * debugging or administrative purposes; not called by the Angular frontend.
     *
     * @return list of all BasketResponse DTOs
     */
    @GetMapping
    public List<BasketResponse> getAllBaskets(){
        return basketService.getAllBaskets();
    }

    /**
     * getBasketById — GET /api/baskets/{basketId}
     *
     * Fetches a single basket by its Redis key. The Angular frontend calls this
     * on app startup to restore the basket from the server (using the basket ID
     * stored in localStorage).
     *
     * @param basketId the basket's string ID (CUID generated by Angular client)
     * @return BasketResponse DTO, or null if no basket with that ID exists in Redis
     */
    @GetMapping("/{basketId}")
    public BasketResponse getBasketById(@PathVariable String basketId){
        return basketService.getBasketById(basketId);
    }

    /**
     * deleteBasketById — DELETE /api/baskets/{basketId}
     *
     * Removes the basket from Redis. Called by Angular after a successful checkout
     * to clean up the basket data.
     *
     * @param basketId the basket's string ID to delete from Redis
     */
    @DeleteMapping("/{basketId}")
    public void deleteBasketById(@PathVariable String basketId){
        basketService.deleteBasketById(basketId);
    }

    /**
     * createBasket — POST /api/baskets
     *
     * Creates a new basket or updates an existing one in Redis (upsert behaviour).
     * Angular sends the entire current basket state on every modification
     * (add item, remove item, change quantity), so this endpoint always receives
     * the full basket, not a diff/patch.
     *
     * Flow:
     *   1. Receive BasketResponse DTO from Angular request body
     *   2. Convert DTO → Basket entity (strip HTTP concern from data layer)
     *   3. Save (upsert) to Redis via BasketService
     *   4. Return the saved BasketResponse with 201 Created
     *
     * @param basketResponse the basket data sent by the Angular client (full state)
     * @return 201 Created with the saved BasketResponse
     */
    @PostMapping
    public ResponseEntity<BasketResponse> createBasket(@RequestBody BasketResponse basketResponse){
        // Convert the incoming DTO to the Redis entity before calling the service
        Basket basket = convertToBasketEntity(basketResponse);
        // Upsert to Redis — returns the saved basket as a DTO
        BasketResponse createdBasket = basketService.createBasket(basket);
        return new ResponseEntity<>(createdBasket, HttpStatus.CREATED);
    }

    /**
     * convertToBasketEntity — maps a BasketResponse DTO to a Basket Redis entity.
     *
     * This conversion is necessary to keep the HTTP layer (DTOs) separate from
     * the data layer (entities). The controller owns this mapping since it bridges
     * the HTTP request body into what the service layer expects.
     *
     * @param basketResponse the DTO received from the Angular client
     * @return a Basket entity ready to be saved to Redis
     */
    private Basket convertToBasketEntity(BasketResponse basketResponse) {
        Basket basket = new Basket();
        basket.setId(basketResponse.getId());  // preserve the client-generated CUID
        basket.setItems(mapBasketItemResponsesToEntities(basketResponse.getItems()));
        return basket;
    }

    /**
     * mapBasketItemResponsesToEntities — converts a list of item DTOs to entity list.
     *
     * Uses Java Streams to map each BasketItemResponse to a BasketItem entity.
     * Stream.map() applies the converter function to every element without mutation.
     *
     * @param itemResponses list of BasketItemResponse DTOs from the request
     * @return list of BasketItem entities
     */
    private List<BasketItem> mapBasketItemResponsesToEntities(List<BasketItemResponse> itemResponses) {
        return itemResponses.stream()
                .map(this::convertToBasketItemEntity)
                .collect(Collectors.toList());
    }

    /**
     * convertToBasketItemEntity — maps a single BasketItemResponse DTO to a BasketItem entity.
     *
     * All fields are copied directly. Note that productBrand and productType are
     * stored as plain strings (denormalised) — no foreign key resolution needed.
     *
     * @param itemResponse the DTO for a single basket item
     * @return a BasketItem entity ready to be stored in Redis
     */
    private BasketItem convertToBasketItemEntity(BasketItemResponse itemResponse) {
        BasketItem basketItem = new BasketItem();
        basketItem.setId(itemResponse.getId());
        basketItem.setName(itemResponse.getName());
        basketItem.setDescription(itemResponse.getDescription());
        basketItem.setPrice(itemResponse.getPrice());
        basketItem.setPictureUrl(itemResponse.getPictureUrl());
        basketItem.setProductBrand(itemResponse.getProductBrand());
        basketItem.setProductType(itemResponse.getProductType());
        basketItem.setQuantity(itemResponse.getQuantity());
        return basketItem;
    }
}
